### ISSUE TITLE
Some MAKI icons not showing properly

### ISSUE THREAD

**Issue by androideveloper** [mapbox/mapbox-plugins-android#865] opened 2019-03-06 13:18 UTC
I use MAKI icons, but some of them doesn't render properly. E.g. marker-15 is shown as dot, but airport-15 is shown properly.

### Steps to reproduce

Demo https://www.dropbox.com/s/yqww9q542r52jvn/MapboxSymbolMAKIIconDemo.zip?dl=0

### Configuration

**Android versions:** 9.0
**Device models:** Xiaomi mi 2 lite
**Mapbox SDK versions:** 7.2.0, plugin-annotation-v7:0.5.0

**Comment by tobrun** [comment] 2019-04-08 09:06
@androideveloper since a coupe of revisions of the mapbox styles we aren't shipping all maki icons anymore with a style. Next to the amount, another change is that are colored upfront. This is expected, we are thinking about ways to improve this with #882.

Not actionable as it's a work as designed. Thank you for reaching out. Closing.

**Closed by tobrun** 2019-04-08 09:06 UTC
Labels: annotation-plugin

**Comment by LukasPaczos** [comment] 2019-04-08 10:34
@androideveloper you can check which sprites are shipped with your style by going to [Mapbox Studio](https://studio.mapbox.com/), selecting your style (or creating a new one out of the core style, like `MAPBOX_STREETS`, that you are using) and inspecting `Images`:
![Screenshot from 2019-04-08 12-30-27](https://user-images.githubusercontent.com/16925074/55717796-6607e400-59fa-11e9-8d56-800c1c4e403a.png)
Only images listed here are going to be available out-of-the-box.
