### ISSUE TITLE
Maps not loading on Android 8.1.0 

### ISSUE THREAD

**Issue by Qirtas** [mapbox/mapbox-plugins-android#899] opened 2019-04-02 05:05 UTC
I am working on an app in which I have integrated mapbox SDK. I have run app on Galaxy J3 having android version 8.1.0, but I could only see a blank white screen instead of map. When I have checked logs, app was throwing this error "loading style failed: Chain validation failed". 
When I run the same app on another phone having android 7.0, app worked perfectly.
Later on, I have downloaded sample app from playstore and the result was same. Getting same error on android 8.1.0 but maps loading fine on older version. 
![Screenshot_20190331-095731_Mapbox Demo](https://user-images.githubusercontent.com/21234281/55377529-c3012700-552e-11e9-9db1-96f753d17d8f.jpg)

![Screenshot_20190331-095739_Mapbox Demo](https://user-images.githubusercontent.com/21234281/55377499-a2d16800-552e-11e9-97b6-ac5f92e07160.jpg)

**Comment by LukasPaczos** [comment] 2019-04-02 07:35
Closing as a duplicate of https://github.com/mapbox/mapbox-android-demo/issues/1008, because https://github.com/mapbox/mapbox-android-demo/issues/1008 provides more information.

**Closed by LukasPaczos** 2019-04-02 07:35 UTC
