### ISSUE TITLE
Annotation “blinks” when updated frequently

### ISSUE THREAD

**Issue by JonasVautherin** [mapbox/mapbox-plugins-android#1043] opened 2019-08-23 12:13 UTC
I receive a steam of GPS locations representing a vehicle, and I show it as an annotation on the map. Showing the annotation is fine.

Whenever I receive a new GPS location, I update the symbol with:

```java
vehicleSymbol.setLatLng(newLatLng);
symbolManager.update(vehicleSymbol);
```

However, the symbol "blinks", apparently mostly when I zoom in. This can be seen on the following video: https://streamable.com/zqhxo

I first posted it on [StackOverflow](https://stackoverflow.com/questions/57595443/annotation-blinks-when-updated-frequently), thinking I may be doing something wrong, but after spending time looking at annotation examples, I'm starting to think it may be a bug.

Any opinion on that?

**Comment by LukasPaczos** [comment] 2019-08-23 12:21
Thanks for reporting the issue @JonasVautherin. Closing as a duplicate of https://github.com/mapbox/mapbox-plugins-android/issues/883.

**Comment by LukasPaczos** [comment] 2019-08-23 12:25
@JonasVautherin on each position change of a symbol, it's going to run collision detection against other symbols and `fade-in`. To disable the collision detection and effectively the unwanted `fade-in`, you can use `SymbolManager.setIconAllowOverlap(true)` like in [this example](https://github.com/mapbox/mapbox-plugins-android/blob/2ae82012c1d7211f97c430c9e72a7ec22c6f1cb5/app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/SymbolActivity.java#L93).

I hope this helps! Closing as resolved.

**Closed by LukasPaczos** 2019-08-23 12:25 UTC
Labels: annotation-plugin, support

**Comment by JonasVautherin** [comment] 2019-08-23 12:48
I see! I was not expecting it to be considered as a new (potentially colliding) symbol. Should be fine then, thanks a lot!
