### ISSUE TITLE
Start symbol dragging without also triggering map click

### ISSUE THREAD

**Issue by zestyping** [mapbox/mapbox-plugins-android#937] opened 2019-04-22 04:07 UTC
When the user attempts to drag a symbol, the touch is also transmitted to the map as a click, triggering the OnMapClickListener.  There doesn't appear to be a way to consume the event in the OnSymbolDragListener, the way there was with markers (an OnMarkerClickListener can return a `boolean` to consume the event, but the OnSymbolDragListener's methods all have a `void` return type).

This makes dragging unusable for apps that also do something in response to map clicks.  For example, in my app, a map click places a marker at the clicked spot, and I would like the user to be able to drag existing markers.  But if I enable dragging, then every time the user drags a marker they also drop another extraneous marker.

Is there any way to distinguish a symbol drag from a map click?

**Comment by tobrun** [comment] 2019-04-24 20:07
Closing as duplicate of https://github.com/mapbox/mapbox-plugins-android/issues/883

**Closed by tobrun** 2019-04-24 20:07 UTC
