### ISSUE TITLE
Don't animate user puck when navigating

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#179] opened 2017-11-21 09:02 UTC
One possible performance improvement for the navigation use-case would be to replace our current layer/source setup with an image when navigating. In this use-case the user puck if fixated at the bottom of the screen and only the bearing changes are animated. This replacement allows to remove the Android SDK animators updating the underlying source and thus saving us cpu cycles + battery.

**Comment by cammace** [comment] 2017-12-22 19:25
duplicate of https://github.com/mapbox/mapbox-plugins-android/issues/215

**Closed by cammace** 2017-12-22 19:25 UTC
Labels: location-layer-plugin
