### ISSUE TITLE
Error in `onAnimationUpdate` of LocationLayerPlugin

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-plugins-android#256] opened 2018-01-26 09:35 UTC
I'm using `LocationLayerPlugin` 0.2.0 and I often got this issue while going around

```
Exception java.lang.Error: vector
com.mapbox.mapboxsdk.style.layers.Layer.nativeSetLayoutProperty (Layer.java)
com.mapbox.mapboxsdk.style.layers.Layer.setProperties (Layer.java:32)
com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin$2.onAnimationUpdate (LocationLayerPlugin.java:590)
android.animation.ValueAnimator.animateValue (ValueAnimator.java:1463)
android.animation.ValueAnimator.animationFrame (ValueAnimator.java:1384)
android.animation.ValueAnimator.doAnimationFrame (ValueAnimator.java:1427)
android.animation.ValueAnimator$AnimationHandler.doAnimationFrame (ValueAnimator.java:759)
android.animation.ValueAnimator$AnimationHandler$1.run (ValueAnimator.java:801)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:911)
android.view.Choreographer.doCallbacks (Choreographer.java:686)
android.view.Choreographer.doFrame (Choreographer.java:619)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:897)
```
Can you please check this?

**Comment by cammace** [comment] 2018-01-27 18:51
Can you up date the plugin version to 0.4.0 and see if that resolved the issue you are seeing?

**Comment by kingfisherphuoc** [comment] 2018-01-28 03:10
@cammace ok, I will try snapshot version 0.4.0 and let you know the result.

**Comment by kingfisherphuoc** [comment] 2018-01-29 11:11
@cammace  I still got this issue:
```
 at com.mapbox.mapboxsdk.style.layers.Layer.nativeSetLayoutProperty(Native Method)
                                                                      at com.mapbox.mapboxsdk.style.layers.Layer.setProperties(Layer.java:32)
                                                                      at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.setLayerBearing(LocationLayer.java:142)
                                                                      at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.setBearing(LocationLayerPlugin.java:610)
                                                                      at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.access$200(LocationLayerPlugin.java:55)
                                                                      at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin$2.onAnimationUpdate(LocationLayerPlugin.java:602)
```

**Comment by cammace** [comment] 2018-01-29 17:10
Could you provide code so I can reproduce the issue, specifically where you are initializing the location layer plugin?

**Comment by kingfisherphuoc** [comment] 2018-01-29 17:59
I do not often get this issue. It is so random. This is my code:

``` 
// initialize in onMapReady()
mLocationLayer = new LocationLayerPlugin(mMapView, mapboxMap, getLocationEngine());
setLocationLayerEnabled(LocationLayerMode.COMPASS);
```
Then I start mocking navigation:
```
// deactive other location engine above first. Then start mock engine below:
setLocationLayerEnabled(LocationLayerMode.NAVIGATION);
getLocationLayerPlugin().setLocationEngine(myMockLocationEngine);
myMockLocationEngine.setLatLngs(mPoints);
myMockLocationEngine.activate();
myMockLocationEngine.startMockingLocation();
```
Below is my `MyMockLocationEngine` class. There's nohing special here, just mock location and update the `LocationLayerPlugin`
```
@SuppressLint("MissingPermission")
public class MyMockLocationEngine extends LocationEngine implements NavigationConfigs {

    public static final String MOCKING_LOCATION = "MockingLocation";
    public static final int DEFAULT_ACCURACY = 20;

    private final int spd; //20m/s
    private static final int MAX_MOCK_DISTANCE = 500; 
    private double remainDistance = 0;

    final private List<Location> locations = new ArrayList<>();
    private List<LatLng> latLngRoutes;
    private Disposable disposable;
    private Random random = new Random();


    public MyMockLocationEngine() {
        this.spd = (int) (MOCKING_SPEED_KM_H / 3.6);
    }

    public void setLatLngs(List<LatLng> latLngs) {

        releaseMockingLocation();
        locations.clear();
        remainDistance = 0;
        this.latLngRoutes = NavigationChecker.simplifyPoints(latLngs);

    }

    /**
     * Chia nhỏ đường để không bị quá dài, chết bộ nhớ.
     */
    private void slideAndCaculateLocation() {
        double distance = 0;

        // Get list of position in a distance
        List<Position> list = new ArrayList<>();

        Iterator<LatLng> iterator = latLngRoutes.iterator();
        LatLng lastLatLng = null;
        while (iterator.hasNext()) {
            LatLng latLng = iterator.next();
            list.add(Position.fromCoordinates(latLng.getLongitude(), latLng.getLatitude()));
            if (lastLatLng == null) {
                lastLatLng = latLng;
            } else {
                distance += lastLatLng.distanceTo(latLng);
                lastLatLng = latLng;
                if (distance >= MAX_MOCK_DISTANCE) {
                    break;
                }
            }
            iterator.remove();
        }

        LineString lineString = LineString.fromCoordinates(list);

        List<Position> positions = new ArrayList<>();
        for (double i = remainDistance; i < distance; i += spd) {
            Point point = TurfMeasurement.along(lineString, i, TurfConstants.UNIT_METERS);
            positions.add(point.getCoordinates());
        }
        // nếu đã đến cuối đường, thì không gọi mock nữa
        if (positions.isEmpty()) {
            return;
        }

        for (int i = 0; i < positions.size() - 1; i++) {
            Position position = positions.get(i);
            Location location = generateMockLocation(position);
            location.setBearing((float) TurfMeasurement.bearing(position, positions.get(i + 1)));
            locations.add(location);
        }

        // Điểm cuối location có bearing = điểm trước nó.
        Location location = generateMockLocation(positions.get(locations.size() - 1));
        location.setBearing(locations.get(locations.size() - 1).getBearing());
        locations.add(location);

        remainDistance = spd - distance % spd;
    }

    private Location generateMockLocation(Position position) {
        Location location = new Location(MOCKING_LOCATION);
        location.setLatitude(position.getLatitude());
        location.setLongitude(position.getLongitude());
        location.setSpeed(spd);
        if (RANDOM_ACCURACY) {
            location.setAccuracy(random.nextInt(200)); // accuray từ 0 - > 200
        } else {
            location.setAccuracy(DEFAULT_ACCURACY);
        }

        return location;
    }


    public void startMockingLocation() {
        // đợi 1s bắt đầu chạy
        disposable = Observable
                .intervalRange(0, Long.MAX_VALUE, 1, 1, TimeUnit.SECONDS)
                .observeOn(AndroidSchedulers.mainThread())
                .doOnNext(new Consumer<Long>() {
                    @Override
                    public void accept(Long aLong) throws Exception {
                        if (locations.isEmpty()) {
                            slideAndCaculateLocation();
                        }
                        // Sau khi tính lại vẫn empty thì quit.
                        if (locations.isEmpty()) {
                            disposable.dispose();
                        }
                        Location location = locations.get(0);
                        locations.remove(0);

                        // Notify những phần khác.
                        for (LocationEngineListener listener : locationListeners) {
                            listener.onLocationChanged(location);
                        }

                        MyLocationService.getInstance().setLocation(location);
                        LocationUpdatedEvent locationUpdatedEvent = LocationUpdatedEvent.generateUpdateEvent(location, false);
                        EventBus.getDefault().post(locationUpdatedEvent);
                    }
                })
                .subscribe();
    }

    public void releaseMockingLocation() {
        if (disposable != null && !disposable.isDisposed()) {
            disposable.dispose();
        }
        disposable = null;
    }

    @Override
    public void activate() {
        for (LocationEngineListener listener : locationListeners) {
            listener.onConnected();
        }
    }

    @Override
    public void deactivate() {
        releaseMockingLocation();
    }

    @Override
    public boolean isConnected() {
        return true;
    }

    @Override
    public Location getLastLocation() {
        return MyLocationService.getInstance().getLastLocation();
    }

    @Override
    public void requestLocationUpdates() {

    }

    @Override
    public void removeLocationUpdates() {
    }

    @Override
    public Type obtainType() {
        return Type.MOCK;
    }
}

```

**Comment by cammace** [comment] 2018-02-15 19:47
> I do not often get this issue. It is so random.

I'm not able to reproduce this issue. Have you only been seeing it with your mock location engine or with other engines also? Are you in compass mode or navigation mode? The crash from 0.4.0 points to the bearing chevron not being accessible to animate but I tested this extensively with no luck producing the crash.

**Comment by kingfisherphuoc** [comment] 2018-02-16 08:09
I got this issue even with the `LostLocationEngine` (provided by Mapbox Sdk). the problem only occurred when I am in `NavigationMode`.

**Comment by cammace** [comment] 2018-02-23 16:58
Do you happen to have a sample project I can use to reproduce the issue? I'm moving this ticket over to the 0.5.0 milestone since we plan to do a release today.

**Comment by kingfisherphuoc** [comment] 2018-02-26 11:35
@cammace  I did change `location` itself  (like snapping Position to routes - lat/long/bearing...) when the `LocationLayer` was updating its location. Was it a problem? Because the `LocationLayer` is bound to `LocationEngine` like below:
```
mLocationLayer = new LocationLayerPlugin(mMapView, mapboxMap, getLocationEngine());
```
I need to add listener to `LocationEngine` to snap location to our routes as below:
```
 locationEngine.addLocationEngineListener(new LocationEngineListener() {
            @Override
            public void onConnected() {
                
            }

            @Override
            public void onLocationChanged(Location location) {
// Check for re-route
// Snap location... such as location.setLatitude(lat), location.setLong.., location.setBearing...
            }
        });
```

**Comment by cammace** [comment] 2018-02-26 14:51
If you are modifying the `Location` object and would like to see the changes reflected within the layer source, it's better to manually update the locationLayer like so:

```java
// Pass in null instead of location engine
mLocationLayer = new LocationLayerPlugin(mMapView, mapboxMap, null);
```

```java
@Override
public void onLocationChanged(Location location) {
  // Check for re-route
  // Snap location... such as location.setLatitude(lat), location.setLong.., location.setBearing...
  mLocationLayer.forceLocationUpdate(snappedLocation)
}
```

> when the LocationLayer was updating its location. Was it a problem? 

Can you elaborate on this a bit more? Is the location getting passed into the locationLayer plugin and then params such as lat/lng and bearing being changed on that same Location object?

**Comment by kingfisherphuoc** [comment] 2018-02-26 20:08
> Can you elaborate on this a bit more? Is the location getting passed into the locationLayer plugin and then params such as lat/lng and bearing being changed on that same Location object?
I mean that after the location changed, I guess the `LocationLayerPlugin` was notified first, then I snapped `Location` with the same `Location` object. Maybe it's the issue. Let me try to resolve it by using `forceLocationUpdate` instead. Thanks!

**Comment by kingfisherphuoc** [comment] 2018-02-27 15:38
@cammace Thank you very much. It seems that the issue is resolved. I will take more time to test, but for first few tests, It was fine.

**Comment by kingfisherphuoc** [comment] 2018-03-19 15:40
It seems that the issue was occurring randomly (I cannot see it in testing but in my Crash analytics there're a lot of reports about this bug). Here's the code I used to update the location:

```java
/**
     * cập nhật vị trí hiện tại
     *
     * @param location
     */
    public synchronized void onLocationChanged(Location location) {
        try {
         
            if (isLocationAccurate(location)) { 
                if (isMoving(location)) {
                    // do snap position, bearing...
                    onMyLocationChanged(location);
                } else {
                    snapLocationIfNeed(location);
                }
                eventRoutingStatus.isGpsStrong = true;
                EventBus.getDefault().post(eventRoutingStatus);
            } else {
                snapLocationIfNeed(location);
                eventRoutingStatus.isGpsStrong = false;
                EventBus.getDefault().post(eventRoutingStatus);
            }
        } finally {
            mMapMvpView.getLocationLayerPlugin().forceLocationUpdate(location);
        }
    }
```
But I still got the below bug:

```java
com.mapbox.mapboxsdk.style.layers.Layer.nativeSetLayoutProperty (Layer.java)
com.mapbox.mapboxsdk.style.layers.Layer.setProperties (Layer.java:32)
com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.setLayerBearing (LocationLayer.java:135)
com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.setBearing (LocationLayerPlugin.java:646)
com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.access$200 (LocationLayerPlugin.java:57)
com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin$2.onAnimationUpdate (LocationLayerPlugin.java:638)
android.animation.ValueAnimator.animateValue (ValueAnimator.java:1374)
android.animation.ValueAnimator.animationFrame (ValueAnimator.java:1298)
android.animation.ValueAnimator.doAnimationFrame (ValueAnimator.java:1339)
android.animation.ValueAnimator$AnimationHandler.doAnimationFrame (ValueAnimator.java:715)
android.animation.ValueAnimator$AnimationHandler.run (ValueAnimator.java:738)
``` 

Is there a way that at least I can avoid app from a fatal crash?
@cammace

**Comment by cammace** [comment] 2018-04-18 19:41
Now that the Map SDK 6.0.1 and the release of Location Layer 0.5.0 is close, I'm assuming this issue doesn't exist anymore since there have been such significant changes on both SDKs. If you update and still have issues, i'll go ahead and reopen this issue and continue looking into it.

**Closed by cammace** 2018-04-18 19:41 UTC
Labels: location-layer-plugin, support
