### ISSUE TITLE
Unable to make space for entry

### ISSUE THREAD

**Issue by affand20** [mapbox/mapbox-plugins-android#945] opened 2019-05-04 12:56 UTC
I have following example [https://docs.mapbox.com/android/plugins/overview/offline/#offline-tile-estimator](here). But when i run it on my device it shows that Unable to make space for entry. I have enable my write external storage too. Please help

![image](https://user-images.githubusercontent.com/28261222/57179307-b9107200-6ea6-11e9-8d44-de41acc54d95.png)

**Comment by LukasPaczos** [comment] 2019-05-08 11:28
Thanks for reaching out @affand20. I believe this is an issue with the cache and not the offline region. Closing as a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/4411.

**Closed by LukasPaczos** 2019-05-08 11:28 UTC
