### ISSUE TITLE
Accuracy circle layer hidden after map movement

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-plugins-android#269] opened 2018-02-02 16:57 UTC
Hey,

I use:
- com.mapbox.mapboxsdk:mapbox-android-sdk:5.3.2
- com.mapbox.mapboxsdk:mapbox-android-navigation:0.9.0
- com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.4.0-SNAPSHOT 

If I move the mapview with the current position, the accuracy circle becomes invisible. 
If I don't move after updates, the accuracy circle is visible.

![ezgif com-crop](https://user-images.githubusercontent.com/23097192/35744897-d6a2225e-0841-11e8-8c9c-f89ff0977a4c.gif)

Any suggestions?

Best regards,
Patrick

**Comment by cammace** [comment] 2018-02-02 19:09
Hey Patrick, the fix for this happened in https://github.com/mapbox/mapbox-plugins-android/pull/245 and is already in master. Looks like the last SNAPSHOT was built 3 days ago on the 29th https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-plugin-locationlayer/0.4.0-SNAPSHOT/. Can you clear your gradle cache and resync your project?

**Comment by P-Zenker** [comment] 2018-02-06 14:13
I can confirm the fix.

But why is the dot like this? It looks like an eye ;)

Google Nexus 6 (Android 7.1)
<img width="228" alt="bildschirmfoto 2018-02-06 um 15 10 56" src="https://user-images.githubusercontent.com/23097192/35863797-10ac43c4-0b50-11e8-9d1a-ca16f07c157c.png">

Samsung S3 (Android 4.3)
![bildschirmfoto 2018-02-06 um 15 10 48](https://user-images.githubusercontent.com/23097192/35863822-2a5c0994-0b50-11e8-974b-2d6df443abf4.png)

**Comment by cammace** [comment] 2018-02-06 19:30
thanks for confirming the original issue has been resolved. I'm currently working on the icons becoming easier to quickly spot and one important enhancement is elevation. This causes the icon to become 3D when the maps tilted. I plan on adding options to adjust all of these behaviors such as elevation. If you want a flat icon on the map like the previous versions had just set elevation to 0 and you'll no longer see 3D effects. One thing to note is that I am still working on this so in the meantime you might see some funny behavior.

**Comment by cammace** [comment] 2018-02-06 19:30
Closing this ticket since @P-Zenker confirmed the issues been fixed.

**Closed by cammace** 2018-02-06 19:30 UTC
Labels: location-layer-plugin
