### ISSUE TITLE
Track SymbolManager image additions?

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-plugins-android#860] opened 2019-03-04 14:51 UTC
Follow up from https://github.com/mapbox/mapbox-navigation-android/pull/1779#issuecomment-469260583

> @LukasPaczos:
> 
> The `SymbolManager` has a feature of keeping annotations alive across style changes. The issue here is, that when the style changes, you're not re-adding the icon image of the marker, so the manager doesn't have a resource to reference anymore.
>
> The gist is, that you need to call something like
>```
>mapView.addOnDidFinishLoadingStyleListener(new MapView.OnDidFinishLoadingStyleListener() {
>  @Override
>  public void onDidFinishLoadingStyle() {
>    mapboxMap.getStyle(new Style.OnStyleLoaded() {
>      @Override
>      public void onStyleLoaded(@NonNull Style style) {
>        Bitmap markerBitmap = ThemeSwitcher.retrieveThemeMapMarker(mapView.getContext());
>        style.addImage(MAPBOX_NAVIGATION_MARKER_NAME, markerBitmap);
>      }
>    });
>  }
>});
>```
> wherever it's best based on the navigation setup. The plugin will take care of the rest.

>> @Guardiola31337:
>>
>> would it make sense for the `SymbolManager` to keep track of this as well?

Cutting this ticket to discuss if it'd make sense and implementation details.

> @LukasPaczos:
>
> adding an image is a separate entry point to the style object and exposing a duplicate method on the manager's side just to track additions would cause confusion imo. But maybe we could rethink that as an options parameter?

cc @LukasPaczos @danesfeder

**Comment by LukasPaczos** [comment] 2019-03-04 14:53
If we'd like to move forward on this, another option would be exposing an interceptor of the `Style` object that would fire callbacks when an element is added.

**Comment by tobrun** [comment] 2019-03-04 16:07
Linking https://github.com/mapbox/mapbox-plugins-android/issues/742 as this could be potentially in scope for that feature.

**Comment by tobrun** [comment] 2019-06-28 11:02
This is moving in https://github.com/mapbox/mapbox-plugins-android/pull/1000, closing this already as it's a dupe of #742

**Closed by tobrun** 2019-06-28 11:02 UTC
Labels: annotation-plugin
