### ISSUE TITLE
error: cannot find symbol method styleUrl(String) with the mapbox-android-plugin-annotation-v7:0.4.0

### ISSUE THREAD

**Issue by topinvestor** [mapbox/mapbox-plugins-android#830] opened 2019-01-27 02:03 UTC
Adding    
 implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.0.1'
 implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.4.0'

in build.gradle 

breaks compatibility leading to:
error: cannot find symbol method styleUrl(String)

when trying to do the following:
    MapboxMapOptions options = new MapboxMapOptions()
                .styleUrl(url)

**Comment by tobrun** [comment] 2019-01-30 11:51
Duplicate of https://github.com/mapbox/mapbox-gl-native/issues/13805

**Closed by tobrun** 2019-01-30 11:51 UTC
