### ISSUE TITLE
Memory leak when using the mapbox-plugins 

### ISSUE THREAD

**Issue by fchen77** [mapbox/mapbox-plugins-android#570] opened 2018-07-04 08:01 UTC
Hi, I'm using mapbox on my android app and it is working great. But when I try to use the locationPlugin to display the user position, I see the consommation of my memory going up when the user move. 
Unfortunately, if the user is constantly moving, the app will crash due to a Out of Memory. 

The issue may be related to the locationEngine.setInterval()/setFastestInterval() since in the doc of both we have : 

> If this rate is faster than your app can handle, you may encounter problems with UI flicker or data overflow

Below is a test that I recreate having the same issue : 

    `
    private LocationLayerPlugin locationPlugin;
    private LocationEngine locationEngine;
    private MapboxMap map;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        super.onCreateView(inflater, container, savedInstanceState);

        Mapbox.getInstance(getContext(), MyMapbox.getToken());

        binding = DataBindingUtil.inflate(inflater, R.layout.test, container, false);
        binding.mapView.onCreate(savedInstanceState);
        binding.mapView.getMapAsync(this);

        return binding.getRoot();
    }

    @Override
    public void onStart() {
        super.onStart();
        binding.mapView.onStart();
    }

    @Override
    public void onResume() {
        super.onResume();
        binding.mapView.onResume();
    }

    @Override
    public void onPause() {
        super.onPause();
        binding.mapView.onPause();
    }

    @Override
    public void onStop() {
        super.onStop();
        binding.mapView.onStop();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        binding.mapView.onLowMemory();
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        if (locationEngine != null) {
            locationEngine.removeLocationUpdates();
            locationEngine.removeLocationEngineListener(this);
            locationEngine.deactivate();
         }

        if (locationPlugin != null) {
            locationPlugin.onStop();
        }
        binding.mapView.onDestroy();
    }

    @Override
    public void onSaveInstanceState(@NonNull Bundle outState) {
        super.onSaveInstanceState(outState);
        binding.mapView.onSaveInstanceState(outState);
    }

    @SuppressLint("MissingPermission")
    @Override
    public void onConnected() {
        locationEngine.requestLocationUpdates();
    }

    @Override
    public void onLocationChanged(Location location) {
        Log.d(LOG_TAG, "TEST");
    }

    private void enableLocationPlugin() {
        if (locationPlugin == null) {
            LocationEngineProvider locationEngineProvider = new LocationEngineProvider(getContext());
            locationEngine = locationEngineProvider.obtainBestLocationEngineAvailable();
            locationEngine.setPriority(LocationEnginePriority.BALANCED_POWER_ACCURACY);
            locationEngine.setFastestInterval(1000);
            locationEngine.setInterval(1000);
            locationEngine.addLocationEngineListener(this);
            locationEngine.activate();

            locationPlugin = new LocationLayerPlugin(binding.mapView, map, locationEngine);
        }
    }

    @Override
    public void onMapReady(MapboxMap mapboxMap) {
        map = mapboxMap;
        enableLocationPlugin();
    }`

**Comment by LukasPaczos** [comment] 2018-07-04 09:56
Hey @fchen77, thanks for reporting this issue! A couple of follow up questions:
- What's the reproduction rate on your device, can you reproduce every single time?
- How long does it take you to reach OOM? 
- Is it reproducible when your device is not connected to the debugger, or your working machine at all?
- Is it reproducible on the latest snapshot build as well?

I know that's a lot of questions, but it would greatly help us to get to the bottom of this, thanks!

**Comment by fchen77** [comment] 2018-07-04 10:40
Hi, @LukasPaczos 

**What's the reproduction rate on your device, can you reproduce every single time?**

The issue is occurring every time   

**How long does it take you to reach OOM?**

This depend on the device I'm using but it take more or less 10 min before reaching OOM. A point that I forget to say was I'm running Lockito (a application) in order to simulate path. I dont' think it's related but I prefer to point it out. 

**Is it reproducible when your device is not connected to the debugger, or your working machine at all?**

Yes, since I use real device in order to do some testing, I'm able to reproduce is issue when my device is not connected. 

**Is it reproducible on the latest snapshot build as well?**

I was using 0.5.2 version, just upgraded to 0.5.3 , and unfortunately the issue is still occurring.  But the memory consommation does feel slower. After 15min, there are still no OOM

**Comment by LukasPaczos** [comment] 2018-07-04 11:20
Thanks @fchen77!

Would you mind retesting that with the `0.6.0-SNAPSHOT` as well? You can find instructions [here](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-locationlayer#getting-started).

Besides that, I just wanted to point out that location updates should be stopped and a call to `LocationLayerPlugin#onStop` should be made in fragment's/activity's `#onStop`.
Also, the call to `LocationLayerPlugin#onStart` should be made in `#onStart`, but that's unrelated to the issue.

**Comment by fchen77** [comment] 2018-07-04 12:16
Yes, I didn't pay attention when writing  the testFragment, but did include the `LocationLayerPlugin#onStop` and the `LocationLayerPlugin#onStart` when doing the test using 0.5.3 version. 

I just tested the snapshot and there is still a constante increase of the memory consummation. 
As for stopping the location update, since I need to constantly keep track of the location, I don't think it is a good solution for me. But yes, adding` LocationEngine#removeLocationUpdates` does resolve the issue but  `LocationEngine#removeLocationEngineListener`

**Comment by fchen77** [comment] 2018-07-05 08:20
I just did new testing using this Code [https://www.mapbox.com/help/android-navigation-sdk/](url) (stopped at **Add Marker On click** step) and I unfortunately run still run into this issue. There won't be memory leak if the device is in lock screen or if the user doesn't move. It does seem to be related to the plugin and since without it there are no increased memory consumption. 

Being unable to really find the source of the issue, I shall try without simulating a route and go for a walk later on the day to see if there are still a OOM.

**Comment by nazmuddin77** [comment] 2018-07-06 09:44
Hi @LukasPaczos,

I've been experiencing the same issue. The easiest way to reproduce this issue is, to enable the location layer plugin and set the zoom of the map to maximum level (somewhere around 18 and above). You can clearly see the rise in memory consumption by the native layer in Android Profiler.
Following were my location layer configurations :
renderMode = COMPASS
cameraMode = TRACKING_COMPASS

My LocationLayerPlugin version is 0.5.3 and Mapbox version is 6.2.1

**Comment by BharathMG** [comment] 2018-07-10 07:45
+1 
I was easily able to reproduce it when the Map is fully zoomed and constantly receiving locations.
I tried creating espresso test showcasing it and you can see the constant increase in memory consumption in native layer when running this test, 

(I changed location to London which has more features in max zoom layer.)

```
 @Test
  fun locationLayerPlugin_increasesMemoryConsumption() {
    val pluginAction = object : GenericPluginAction.OnPerformGenericPluginAction<LocationLayerPlugin> {
      override fun onGenericPluginAction(plugin: LocationLayerPlugin, mapboxMap: MapboxMap,
                                         uiController: UiController, context: Context) {
        val testLifecycleOwner = TestLifecycleOwner()
        testLifecycleOwner.markState(Lifecycle.State.RESUMED)
        testLifecycleOwner.lifecycle.addObserver(plugin)
       val initLocation = Location("test")
        initLocation.latitude = 51.5074
       initLocation.longitude = 0.1278
        mapboxMap.moveCamera(CameraUpdateFactory.newLatLng(LatLng(initLocation)))
        mapboxMap.moveCamera(CameraUpdateFactory.zoomBy(18.0))
        for (i in 0..10000) {
          plugin.forceLocationUpdate(initLocation)
          uiController.loopMainThreadForAtLeast(100)
        }
      }
    }
    executePluginTest(pluginAction,
            PluginGenerationUtil.getLocationLayerPluginProvider(rule.activity))
  }
```

**Comment by LukasPaczos** [comment] 2018-07-10 17:05
Thanks for notes @nazmuddin77, @BharathMG!
I'm again able to kind-of consistently reproduce the issue and working on a solution.

**Comment by LukasPaczos** [comment] 2018-07-11 09:29
Thanks everyone involved for code snippets and testing! The issue seems to be resolved with https://github.com/mapbox/mapbox-gl-native/pull/12296 that will be included in the `0.7.0` release targeted EOW next week.

In the meantime, could you retest your implementations while manually including Maps SDK snapshot dependency?
```
implementation "com.mapbox.mapboxsdk:mapbox-android-sdk:6.3.0-SNAPSHOT"
```

**Comment by fchen77** [comment] 2018-07-11 17:37
Just did some testing using both snapshot 6.3.0 and 0.7.0 and so far I don't get any OOM or excess memory consumption.

**Comment by LukasPaczos** [comment] 2018-07-12 08:17
Great, thanks for verifying that @fchen77!

**Comment by fladouceur** [comment] 2018-07-12 20:46
I've been having the exact same issue, and I've also just tested with snapshots 6.3.0 and 0.7.0 which seem to have resolved most of it.

However I have a case where the crash still happens after a few minutes exactly as before, caused by setting the render mode to compass:
`if (mLocationLayerPlugin == null) {
                    mLocationLayerPlugin = new LocationLayerPlugin(mapView, mMapboxMap, mLocationEngine);
                    mLocationLayerPlugin.setRenderMode(RenderMode.COMPASS);
                }`

if I comment out the line then no more crashing. Hopefully you can include a fix for it in the upcoming release..! Cheers

**Comment by LukasPaczos** [comment] 2018-07-19 10:56
I run various tests with render mode being set to `RenderMode.COMPASS` and can't reproduce the issue @fladouceur. Would you be able to provide a full example?

**Comment by LukasPaczos** [comment] 2018-07-19 10:58
This is fixed with https://github.com/mapbox/mapbox-plugins-android/pull/585.

**Closed by LukasPaczos** 2018-07-19 10:58 UTC
Labels: location-layer-plugin
