### ISSUE TITLE
Markers are bugged on the map (images become grayish/black)

### ISSUE THREAD

**Issue by vladoski** [mapbox/mapbox-plugins-android#1082] opened 2019-12-23 21:14 UTC
Hi devs, I'm using your APIs to make a simple mock game.  
I've encountered that the half of the time when I'm using the map, the markers are bugged. They become greyish with no reason whatsoever. While zooming in/out the glitch might appear or disappear.
I've tried the app only on the Android Studio built-in emulator (Pixel 3 API 29) on multiple PCs.

Here all the markers are bugged:
![bugged_markers](https://user-images.githubusercontent.com/9903174/71380575-0e34fb80-25d0-11ea-89eb-64f1fced8742.png)

Here only some of them are bugged:
![bugged_markers_2](https://user-images.githubusercontent.com/9903174/71380603-34f33200-25d0-11ea-9887-7cab75f46383.png)

Here's an example of how should the map look with no bugged markers:
![not_bugged_icons](https://user-images.githubusercontent.com/9903174/71380610-40465d80-25d0-11ea-80c6-dc00da9461b0.png)

If you need it, here's the MainActivity code: https://gist.github.com/vladoski/b98aee5c664fd9e7ede4faa084f13842

Thanks for your cooperation!

**Comment by vladoski** [comment] 2019-12-31 11:20
I've found that this bug doesn't happen when I use my OnePlus 6 instead of the Pixel 3 emulator.

**Comment by langsmith** [comment] 2019-12-31 14:23
I'm glad that it's working fine for you on your physical device. There are known issues with displaying some icon colors on an emulator. Closing this as it's a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/10829. Thanks for using Mapbox.

**Closed by langsmith** 2019-12-31 14:23 UTC
