### ISSUE TITLE
Not seeing location layer marker after upgrading mapbox

### ISSUE THREAD

**Issue by stoefln** [mapbox/mapbox-plugins-android#510] opened 2018-05-14 13:12 UTC
After upgrading to MapBox 6.01 and Location Layer Plugin 0.5.2 I don't see a marker anymore.
I figured out that adding a LocationEngine solves the issue, however we have a complicated architecture which includes a LocationService, which makes using the LocationEngine more complicated. Do I really need a LocationEngine and when did that requirement change?

**Comment by cammace** [comment] 2018-05-14 19:15
Hey there @stoefln, first, to address your versioning. If you are including the Location Layer Plugin inside your app as a dependency, you no longer need to also include the Mapbox Map SDK dependency since the Location Layer offers the SDK and correct version of it transitively. This might be the issue with not seeing the Location Layer.

> Do I really need a LocationEngine and when did that requirement change?

No, you shouldn't need to provide a LocationEngine when using the Location Layer Plugin. Being able to manually update the location layer is a designed feature specifically for use cases like yours, this is why the param is annotated `nullable`. Could you provide snippets of code that I can use to reproduce the issue, specifically around initializing the Location Layer and manually providing updates.

**Comment by cammace** [comment] 2018-05-19 20:27
Closing for now but can revisit once more information is provided.

cc: @zugaldia

**Closed by cammace** 2018-05-19 20:27 UTC
Labels: location-layer-plugin, question

**Comment by stoefln** [comment] 2018-05-24 13:36
@cammace I cleaned my code so I can figure out why it's not working without locationEngine. Now its really simple and it's basically just:
```
          locationEngine = new 
 LocationEngineProvider(getContext()).obtainBestLocationEngineAvailable();
            locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
            locationEngine.activate();
            locationEngine.addLocationEngineListener(new LocationEngineListener() {
                @Override
                public void onConnected() {
                    Timber.d("xxx onConnected");
                    locationEngine.requestLocationUpdates();
                }

                @Override
                public void onLocationChanged(Location location) {
                    Timber.d("xxx onLocationChanged");
                    originLocation = location;
                }
            });
// with locationEngine, everything works. not providing does not work
            locationPlugin = new LocationLayerPlugin(mapView, getMapboxMap(), null);
            locationPlugin.setLocationLayerEnabled(true);
            locationPlugin.setCameraMode(CameraMode.TRACKING_GPS);
            locationPlugin.setRenderMode(RenderMode.GPS);

            locationPlugin.onStart();
```

**Comment by danesfeder** [comment] 2018-05-24 19:35
Hey @stoefln 👋  [this constructor](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin.java#L94) will initialize the `LocationEngine` for you.  

You should be able to drop that `null` param and get it working that way:
```
new LocationLayerPlugin(mapView, getMapboxMap());
```

I also opened #539 to initialize the default engine if `null` is passed like you're doing in this code snippet.  We should do this or set those annotations to `@NonNull` to prevent this type of confusion.  Thanks for checking out the plugin!

**Comment by stoefln** [comment] 2018-05-28 09:57
@danesfeder no, there is no constructor without LocationEngine param. Not in 0.5.2 at least...

**Comment by zugaldia** [comment] 2018-05-28 12:26
@stoefln Looks like this feature was added in 0.5.3 https://github.com/mapbox/mapbox-plugins-android/issues/532, could you give that version a try when you have a chance?
