### ISSUE TITLE
Marker for Places and Location icon turns black

### ISSUE THREAD

**Issue by ferily7** [mapbox/mapbox-plugins-android#561] opened 2018-06-27 18:07 UTC
I implemented the user's location plugin and the places plugin in my app. However, when I zoom in and out of the map, the marker turns black at times. I'm having the same problem with the location icon - when I zoom in or out, the icon turns black. Is there a specific reason why this is happening? (Also this isn't related to the plugins but even with the layers I added to the map, they sometimes turn black when I zoom in or out.. At times you can see a part of the layer (the color) but the rest of it is black)

![screenshot_1530122763](https://user-images.githubusercontent.com/13490770/41991419-33c2574a-79fa-11e8-9edd-6cac29d7d04d.png)
![screenshot_1530122693](https://user-images.githubusercontent.com/13490770/41991421-33d9e126-79fa-11e8-8272-2c747312844b.png)
![screenshot_1530122772](https://user-images.githubusercontent.com/13490770/41991422-33efcb62-79fa-11e8-94a9-d0e9cb920924.png)
![screenshot_1530122781](https://user-images.githubusercontent.com/13490770/41991423-340757f0-79fa-11e8-8d57-42712c3abcf7.png)

**Comment by ferily7** [comment] 2018-06-27 18:13
I think it'll be helpful if I upload my code for the two plugins too?

    `@Override
    public void onMapReady(MapboxMap mapboxMap) {
        map = mapboxMap;

        // Users location plugin
        enableLocationPlugin();

        // Real-time Traffic Plugin
        //trafficPlugin = new TrafficPlugin(mapView, mapboxMap);
        //trafficPlugin.setVisibility(true); // Enable the traffic view

        // Places Plugin
        initSearchFab();
        addUserLocations();

        // Add the symbol layer icon to map for future use
        Bitmap icon = BitmapFactory.decodeResource(
                MainActivity.this.getResources(), R.drawable.custom_marker);
        mapboxMap.addImage(symbolIconId, icon);

        // Create an empty GeoJSON source using the empty feature collection
        setUpSource();

        // Set up a new symbol layer for displaying the searched location's feature coordinates
        setupLayer();
    }

    private void initSearchFab() {
        FloatingActionButton searchFab = findViewById(R.id.fab_location_search);
        searchFab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new PlaceAutocomplete.IntentBuilder()
                        .accessToken(Mapbox.getAccessToken())
                        .placeOptions(PlaceOptions.builder()
                                .backgroundColor(Color.parseColor("#EEEEEE"))
                                .addInjectedFeature(home)
                                .addInjectedFeature(work)
                                .limit(10)
                                .build(PlaceOptions.MODE_CARDS))
                        .build(MainActivity.this);
                startActivityForResult(intent, REQUEST_CODE_AUTOCOMPLETE);
            }
        });
    }

    private void addUserLocations() {
        home = CarmenFeature.builder().text("Mapbox SF Office")
                .geometry(Point.fromLngLat(-122.399854, 37.7884400))
                .placeName("85 2nd St, San Francisco, CA")
                .id("mapbox-sf")
                .properties(new JsonObject())
                .build();

        work = CarmenFeature.builder().text("Mapbox DC Office")
                .placeName("740 15th Street NW, Washington DC")
                .geometry(Point.fromLngLat(-77.0338348, 38.899750))
                .id("mapbox-dc")
                .properties(new JsonObject())
                .build();
    }

    private void setUpSource() {
        GeoJsonSource geoJsonSource = new GeoJsonSource(geojsonSourceLayerId);
        map.addSource(geoJsonSource);
    }

    private void setupLayer() {
        SymbolLayer selectedLocationSymbolLayer = new SymbolLayer("SYMBOL_LAYER_ID", geojsonSourceLayerId);
        selectedLocationSymbolLayer.withProperties(PropertyFactory.iconImage(symbolIconId));
        map.addLayer(selectedLocationSymbolLayer);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (resultCode == Activity.RESULT_OK && requestCode == REQUEST_CODE_AUTOCOMPLETE) {

            // Retrieve selected location's CarmenFeature
            CarmenFeature selectedCarmenFeature = PlaceAutocomplete.getPlace(data);

            // Create a new FeatureCollection and add a new Feature to it using selectedCarmenFeature above
            FeatureCollection featureCollection = FeatureCollection.fromFeatures(
                    new Feature[]{Feature.fromJson(selectedCarmenFeature.toJson())});

            // Retrieve and update the source designated for showing a selected location's symbol layer icon
            GeoJsonSource source = map.getSourceAs(geojsonSourceLayerId);
            if (source != null) {
                source.setGeoJson(featureCollection);
            }

            // Move map camera to the selected location
            CameraPosition newCameraPosition = new CameraPosition.Builder()
                    .target(new LatLng(((Point) selectedCarmenFeature.geometry()).latitude(),
                            ((Point) selectedCarmenFeature.geometry()).longitude()))
                    .zoom(14)
                    .build();
            map.animateCamera(CameraUpdateFactory.newCameraPosition(newCameraPosition), 4000);
        }
    }

    private void enableLocationPlugin() {
        // Check if permissions are enabled and if not request
        if (PermissionsManager.areLocationPermissionsGranted(this)) {
            initializeLocationEngine();
            initializeLocationLayer();
        } else {
            permissionsManager = new PermissionsManager(this);
            permissionsManager.requestLocationPermissions(this);
        }
    }

    @SuppressWarnings( {"MissingPermission"})
    private void initializeLocationEngine() {
        locationEngine = new LocationEngineProvider(this).obtainBestLocationEngineAvailable();
        locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
        locationEngine.activate();

        Location lastLocation = locationEngine.getLastLocation();
        if (lastLocation != null) {
            originLocation = lastLocation;
            setCameraPosition(lastLocation);
        } else {
            locationEngine.addLocationEngineListener(this);
        }
    }

    @SuppressWarnings( {"MissingPermission"})
    private void initializeLocationLayer() {
        locationLayerPlugin = new LocationLayerPlugin(mapView, map, locationEngine);
        locationLayerPlugin.setLocationLayerEnabled(true);
        locationLayerPlugin.setCameraMode(CameraMode.TRACKING);
        locationLayerPlugin.setRenderMode(RenderMode.NORMAL);
    }

    private  void setCameraPosition(Location location) {
        map.animateCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(location.getLatitude(), location.getLongitude()), 13.0));
    }

    @Override
    @SuppressWarnings( {"MissingPermission"})
    public void onConnected() {
        locationEngine.requestLocationUpdates();
    }

    @Override
    public void onLocationChanged(Location location) {
        if (location != null) {
            originLocation = location;
            setCameraPosition(location);
        }
    }

    @Override
    public void onExplanationNeeded(List<String> permissionsToExplain) {
        Toast.makeText(this, "Need permission to enable location", Toast.LENGTH_LONG).show();
    }

    @Override
    public void onPermissionResult(boolean granted) {
        if (granted) {
            enableLocationPlugin();
        } else {
            Toast.makeText(this, "You have not enabled your location", Toast.LENGTH_LONG).show();
            finish();
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        permissionsManager.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    @Override
    @SuppressWarnings( {"MissingPermission"})
    public void onStart() {
        super.onStart();
        if (locationEngine != null) {
            locationEngine.requestLocationUpdates();
        }
        if (locationLayerPlugin != null) {
            locationLayerPlugin.onStart();
        }
        mapView.onStart();
    }

    @Override
    public void onResume() {
        super.onResume();
        mapView.onResume();
    }

    @Override
    public void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    public void onStop() {
        super.onStop();
        if (locationEngine != null) {
            locationEngine.removeLocationUpdates();
        }
        if (locationLayerPlugin != null) {
            locationLayerPlugin.onStop();
        }
        mapView.onStop();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (locationEngine != null) {
            locationEngine.deactivate();
        }
        mapView.onDestroy();
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }

`

**Comment by LukasPaczos** [comment] 2018-06-29 11:11
Hey @ferily7, thanks for reaching out!
At first glance, your code looks fine. This issue looks like https://github.com/mapbox/mapbox-gl-native/issues/10829. Are you using an emulator or a physical device? If the former, could you retest on a physical device?

**Comment by ferily7** [comment] 2018-06-29 17:11
Hi @LukasPaczos ! Thank you for the reply! I am actually using an emulator on my laptop so maybe that's where the issue is arising? I actually do not have a physical device... Is the reason why my layers and marker turn black is because I'm using an emulator? I'm not sure if I use a physical android device that will solve the problem. Is another possibility some version I'm using?

**Comment by LukasPaczos** [comment] 2018-06-29 17:50
Yes, the issue is definitely caused by the emulator and, unfortunately, we don't have any quick fixes at the moment. You can navigate to the emulator settings -> advanced and try different renderer settings but other than that I can only recommend using a physical device.

Closing as not actionable. I you happen to retest this on a physical device, please let us know if the issue persists.

**Closed by LukasPaczos** 2018-06-29 17:50 UTC

**Comment by ArnyminerZ** [comment] 2020-04-25 11:36
Hi, I am having the same issue, but on a physical device. I am using a Pixel 3a.
I made the app show a dialog so I know the bitmap is well loaded. See this pic:
![Screenshot_20200425-133255](https://user-images.githubusercontent.com/12086466/80278805-956abb00-86f9-11ea-9e4f-d06f007d05ea.png)
But the only thing the map shows is:
![Screenshot_20200425-133300](https://user-images.githubusercontent.com/12086466/80278811-a3204080-86f9-11ea-87db-f235e73d2e3a.png)

Any ideas of what can be happening? I am using `com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0` and `com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0`

**Comment by Cloud9Clone** [comment] 2020-05-05 19:11
In the emulator, there is a black dot by me as well, but on a real device like Xiaomi 9T, there is no problem. (Sometimes, when I place very fast different locations from the emulator I see for little period of time the blue dot with white border)

**Comment by johnnyhoichuen** [comment] 2020-07-16 09:20
Make sure the last argument is `false`
`style.addImage(IMAGE_ID, BitmapUtils.getBitmapFromDrawable(getResources().getDrawable(R.drawable.some_image)), false);`

**Comment by PhanVanLinh** [comment] 2022-04-28 03:05
The default of last argument (sdf: Boolean) in mapbox v10 is already false, but this issue is still happened on emulator
```
fun addImage(
    imageId: String,
    image: Image
  ): Expected<String, None> = addImage(imageId, image, false)
```
