### ISSUE TITLE
Mapbox Places search does not work..

### ISSUE THREAD

**Issue by erluxman** [mapbox/mapbox-plugins-android#976] opened 2019-06-05 03:13 UTC
Mapbox Along with its places API were working well with following config 
   ```
   val mapbox = "7.1.1"
    val geoJsonCore = "4.3.0"
    val mapBoxAnnotationPlugin = "0.4.0"
    val mapBoxPlacesPlugin = "0.7.0"
```

But after I upgraded it to following versions it's showing offline option or retry but it does nothing..

  ```
 val mapbox = "8.0.0"
    val geoJsonCore = "4.8.0"
    val mapBoxAnnotationPlugin = "0.6.0"
    val mapBoxPlacesPlugin = "0.8.0"
```
<img width="328" alt="Screen Shot 2019-06-05 at 8 28 15 AM" src="https://user-images.githubusercontent.com/6260014/58927820-d8354480-876f-11e9-9d0f-23810cd57259.png">

Are the new sets of config incompatible??

**Comment by tobrun** [comment] 2019-06-10 07:47
cc @langsmith @zugaldia

**Comment by langsmith** [comment] 2019-06-10 23:45
Hey @erluxman , thanks for using Mapbox. 

I set up a new project to try your dependency mix. I set up a completely new Android app following https://www.mapbox.com/install/android/. Then I added these dependencies, which I believe would match what you listed above. 

```groovy
implementation 'com.mapbox.mapboxsdk:mapbox-sdk-core:4.8.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.0.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v7:0.8.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.6.0'
```

Then I added the following inside of the `onStyleLoaded()` callback.

```java
findViewById(R.id.go_to_search_activity_button).setOnClickListener(new View.OnClickListener() {
              @Override
              public void onClick(View view) {
              
                Intent intent = new PlaceAutocomplete.IntentBuilder()
                  .accessToken(ACCESS_TOKEN)
                  .placeOptions(PlaceOptions.builder()
                    .backgroundColor(Color.parseColor("#EEEEEE"))
                    .limit(10)
                    .build(PlaceOptions.MODE_CARDS))
                  .build(MainActivity.this);
                startActivityForResult(intent, REQUEST_CODE_AUTOCOMPLETE);
                
              }
});
```

When I started typing a geocoding search, I got the same `Offline - Try again` message you did.

![Screen Shot 2019-06-10 at 2 12 53 PM](https://user-images.githubusercontent.com/4394910/59229821-59397500-8b90-11e9-8a63-13630ef95af0.png)

Mention of stuff such as `CarmenFeatureConverter.toCarmenFeature`, `GeometryDeserializer.deserialize`, `PointDeserializer.deserialize`, got me looking into various Java SDK versions.  

Similar error(s) when I tried injecting `home` and `work` into the autocomplete UI

![Screen Shot 2019-06-10 at 1 45 23 PM](https://user-images.githubusercontent.com/4394910/59231165-8daf3000-8b94-11e9-83e0-9481c3c5b8da.png)

**Then** I switched [to the `0.9.0-SNAPSHOT`](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-places#getting-started) (`implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v7:0.9.0-SNAPSHOT'
`) and got the Places Plugin to work just fine with the above setup.

I think this issue is about `Feature` serialization, which was probably addressed by https://github.com/mapbox/mapbox-java/pull/1034. The last Places Plugin release was April 8th (https://github.com/mapbox/mapbox-plugins-android/releases) and ["bump java services version to v4.6.0" happened 19 days ago](https://github.com/mapbox/mapbox-plugins-android/commits/master/plugin-places), which means that #1034 is only available in the Places Plugin `0.9.0-SNAPSHOT`. In my own testing, I **did** get geocoding search UI autocomplete working as intended when using the `SNAPSHOT`.

Seems that the plugin repo's Java SDK dependency didn't keep up with [the Java releases](https://github.com/mapbox/mapbox-java/issues?q=is%3Aissue+release+is%3Aclosed). I've updated https://github.com/mapbox/mapbox-java/issues/1024, so that future release checklists include a reminder to `Update the plugin dependency file`. 

My guess is that bumping the Java SDK dependency version in the plugins repo (pr for this is at https://github.com/mapbox/mapbox-plugins-android/pull/985) and then releasing a new version of the Places Plugin will solve this issue.

Also probably related to this is https://github.com/mapbox/mapbox-java/issues/1044#issuecomment-500632697

**Comment by erluxman** [comment] 2019-06-11 09:52
@langsmith  thanks for the hard work, waiting for that release..

**Comment by erluxman** [comment] 2019-06-11 09:53
@langsmith  I also got his issue https://github.com/mapbox/mapbox-gl-native/issues/14849 after the same upgrades, any chances you can confirm these will be fixed in the new release?

**Comment by langsmith** [comment] 2019-06-13 17:24
> @langsmith thanks for the hard work, waiting for that release..

@erluxman , new release of the Places Plugin went out a couple of days ago https://github.com/mapbox/mapbox-plugins-android/issues/987.  I'm going to close this ticket because the release should've solved this ticket.

>I also got his issue mapbox/mapbox-gl-native#14849 after the same upgrades, any chances you can confirm these will be fixed in the new release?

Thanks for making that ticket. I/we haven't gotten around to looking into this just quite yet. Going to close this ticket also so that we can keep conversation about https://github.com/mapbox/mapbox-gl-native/issues/14849 on the https://github.com/mapbox/mapbox-gl-native/issues/14849 ticket 👍 .

**Closed by langsmith** 2019-06-13 17:24 UTC
Labels: places-plugin
