### ISSUE TITLE
[Android] onAddMapClickListener and onSymbolClickListener happens at the same time

### ISSUE THREAD

**Issue by tuyen-vuduc** [mapbox/mapbox-plugins-android#1053] opened 2019-09-14 11:50 UTC
Hi,

I tried to add listener to both MapClick and SymbolClick.

If MapClick event handler returns true, then SymbolClick event handler is skipped.

I think it should be reserved because Symbol are on top of the map. In the other words, if Symbol event handler is attached, MapClick should be skipped always.

Please advise if any other solutions in case.

Thanks.

**Comment by LukasPaczos** [comment] 2019-09-19 09:26
Closing as a duplicate of https://github.com/mapbox/mapbox-plugins-android/issues/966.

**Closed by LukasPaczos** 2019-09-19 09:26 UTC
Labels: annotation-plugin
