### ISSUE TITLE
Draw a Line above a FillExtrusion

### ISSUE THREAD

**Issue by ANGerz** [mapbox/mapbox-plugins-android#983] opened 2019-06-07 13:27 UTC
I am currently working with a `FillExtrusion` and a `LineManager`. I wish to display the lines _above_ the extrusion rendering. 
I use `mapStyle?.addLayerBelow(extrusion, SymbolManager.ID_GEOJSON_LAYER)` but this not working. `extrusion` is my `FillExtrusion`. 
The shape is well drawn and the lines too, but the lines is under the 3D. 

It may be odd to asks this, but how I can display the line above the 3D shape ? But since the Symbols annotations are displayed above the 3D shapes, I guess that Lines could be also displayed above.

Thanks you in advance.

**Comment by snkashis** [comment] 2019-06-24 18:10
I could be wrong, but this might be a dupe of https://github.com/mapbox/mapbox-gl-native/issues/14779

**Comment by tobrun** [comment] 2019-06-28 11:53
@snkashis yes, upstream bug

**Closed by tobrun** 2019-06-28 11:53 UTC
