### ISSUE TITLE
LocationLayerPlugin not visible after setting mapStyleUrl or random crashes

### ISSUE THREAD

**Issue by vladgheorghe** [mapbox/mapbox-plugins-android#470] opened 2018-04-30 00:40 UTC
Hello, in onMapReady I am initializing the locationlayerplugin. Immediately after I am setting the map style through the method map.setMapStyleUrl. The plugin is not visible and sometimes we are experiencing crashes immediately after the callback onStyleLoaded gets called. Reproduces always on 0.5.0 with maps sdk 6.0.1

**Comment by cammace** [comment] 2018-04-30 14:51
I'll add a test case for this. In https://github.com/mapbox/mapbox-plugins-android/blob/master/app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerTest.kt#L166, we are setting the location layer plugin up first and then changing the map style. Opposite of what you're doing.

**Comment by cammace** [comment] 2018-04-30 17:52
I wrote a new Isolated test class for the Location Layer Plugin which just uses a default `SupportMapFragment` as the view. then, I went through the steps to try reproducing your issue but it seems no matter where I change the map style, the Location Layer seems to handle the change fairly well. You can see the test in https://github.com/mapbox/mapbox-plugins-android/pull/471. Feel free to comment on this issue or the PR if I got something wrong. 

Is there a reason for changing the map style immediately when the mapReady callback is invoked? It's better to initialize your map style through XML or MapboxMapOptions if you can that way when the maps initially rendered it uses your style rather than downloading the default Street style first and then switching to your desired style.

**Comment by cammace** [comment] 2018-05-02 15:32
Since I wasn't able to reproduce this issue in #470, I am going ahead and closing this ticket. Will reopen if you are still running into issues and my test wasn't testing your use case.

**Comment by vladgheorghe** [comment] 2018-05-02 17:37
Unfortunately, it seems that I am experiencing a different behaviour. I'm posting the code I am using and an attachment of the bug reproducing.

```
public void onMapReady(MapboxMap mapboxMap) {
        map = mapboxMap;
        map.getUiSettings().setTiltGesturesEnabled(false);
        initCamera();
        initLocationLayer();
        //this gets based on user prefences
       map.setStyleUrl(MAPBOX_DAY_STYLE_URL,  MainActivity.this);

    @SuppressWarnings({"MissingPermission"})
    private void initLocationLayer() {
        LocationLayerOptions options = LocationLayerOptions.builder(this)
                .padding(mapViewPadding)
                .bearingDrawable(R.drawable.icon_bearing)
                .gpsDrawable(R.drawable.icon_user_puck)
                .build();
        locationLayer = new LocationLayerPlugin(mapView, map, locationEngine, options);
        locationLayer.setLocationLayerEnabled(true);
        locationLayer.setRenderMode(RenderMode.GPS);
        locationLayer.setCameraMode(CameraMode.NONE);

        if (CURRENT_LOCATION != null) {
            locationLayer.forceLocationUpdate(CURRENT_LOCATION);
        }
    }
```

Please let me know if I am doing anything wrong.

[Recording of bug here.]()

**Comment by vladgheorghe** [comment] 2018-05-02 17:47
Reproduces every time for me, on multiple devices. I am using maps sdk 6.0.1, location layer 0.5.0 and the latest version of 0.13.0-SNAPSHOT navi

**Comment by vladgheorghe** [comment] 2018-05-02 17:56
I'm now using the mapView.setStyleUrl method to set the style before the map gets loaded. Thank you for giving me the tip, it helped optimize quite a bit. However the problem still persists when changing the style after the map loads. I tried with both mapView.setStyleUrl and map.setStyleUrl. 

Also, I'm seeing many these logs in logcat after setting the style for a few seconds:

05-02 20:54:04.265 22939-23032/ro.ascendnet.android.startaxi.taximetrist W/mbgl: {GLThread 822}[Render]: can't find source for layer 'mapbox-location-shadow'
05-02 20:54:04.266 22939-23032/ro.ascendnet.android.startaxi.taximetrist W/mbgl: {GLThread 822}[Render]: can't find source for layer 'mapbox-location-accuracy-layer'
05-02 20:54:04.266 22939-23032/ro.ascendnet.android.startaxi.taximetrist W/mbgl: {GLThread 822}[Render]: can't find source for layer 'mapbox-location-stroke-layer'
05-02 20:54:04.266 22939-23032/ro.ascendnet.android.startaxi.taximetrist W/mbgl: {GLThread 822}[Render]: can't find source for layer 'mapbox-location-layer'

**Comment by cammace** [comment] 2018-05-02 18:50
Thanks for the additional info. I checked out the last commit that we used to do the 0.5.0 release and was able to reproduce what you are experiencing. The good news is that, since the release, we have resolved this issue (not sure what PR fixed this). For now, you can try out the SNAPSHOT which includes a bunch of bug fixes including the one you are talking about. Our README gives instructions on how to setup using the SNAPSHOT. I plan to do a 0.5.1 bug release later this week or next. Hope this helps!

**Comment by vladgheorghe** [comment] 2018-05-02 22:11
I can confirm that it’s fixed on 0.6.0 snapshot, thank you very much for the fast reply cameron !

**Comment by vladgheorghe** [comment] 2018-05-04 16:17
It seems that with the latest snapshot version the bug re-appeared, i'm still using 0.6.0-snapshot

**Comment by cammace** [comment] 2018-05-04 16:43
Nice catch, just tested on master, certainly appears to have come from this merge https://github.com/mapbox/mapbox-plugins-android/pull/476. Will look into fixing.

**Comment by cammace** [comment] 2018-05-09 15:04
https://github.com/mapbox/mapbox-plugins-android/pull/483 fixes this issue for now (really just a bandaid to get this 0.5.1 release out). Closing

**Closed by cammace** 2018-05-09 15:04 UTC
Labels: bug, location-layer-plugin

**Comment by vladgheorghe** [comment] 2018-05-11 17:39
Ehm... even with 0.5.2 release this is still happening, these are the dependencies I'm using

    // MAPBOX

    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.0.1'

    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.13.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.13.0'

    implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:3.2.0-SNAPSHOT'

    implementation 'com.mapzen.android:lost:3.0.4'

    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.2'

**Comment by cammace** [comment] 2018-05-11 21:39
You should be able to remove a bunch of these dependencies so that your dependency versions become transitive through the `navigation-ui` dependency. You'll run into way fewer dependency conflicts in this case, the other option is to exclude dependencies from others to ensure no conflicts arise. 

```groovy
// MAPBOX
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.13.0'
```

We strongly suggest moving away from the LOST dependency, this project hasn't been actively worked on in awhile so we dropped support for it.
